import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="w-full bg-gray-700 text-white">{children}</div>
      </body>
    </html>
  );
}
